# Generated by Django 3.0 on 2019-12-31 02:05

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, upload_to=users.models.user_directory_path),
        ),
    ]
