# Generated by Django 3.0 on 2020-01-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='career_path',
            field=models.CharField(default='IT', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='class_number',
            field=models.CharField(default='0000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.CharField(default='n/a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='employment_status',
            field=models.CharField(default='1', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='start_time',
            field=models.CharField(default='2', max_length=2),
            preserve_default=False,
        ),
    ]
