# Generated by Django 3.0 on 2020-01-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191231_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='career_path',
            field=models.CharField(choices=[('IT', 'IT'), ('FIN', 'Finance'), ('PHA', 'Pharmaceutical'), ('ACA', 'Academia'), ('OTH', 'Other')], max_length=5),
        ),
    ]
