# Generated by Django 3.0 on 2020-01-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191231_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='employment_status',
            field=models.CharField(choices=[('1', 'Looking for Jobs'), ('2', 'Looking for Candidates'), ('3', 'Both')], max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='start_time',
            field=models.CharField(choices=[('1', 'In 2 weeks'), ('2', 'In a month'), ('3', 'In 3 months'), ('4', 'In 6 months')], max_length=2),
        ),
    ]
